name: Generate Kicad Outputs

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  AUTO_TAG_NAME: ${{ github.ref_name }}_${{ github.sha }}
  PROJ_NAME: ghost_bot

jobs:
  kicad_generation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Install Linux Dependencies
      run: |
            sudo add-apt-repository ppa:kicad/kicad-8.0-releases
            sudo apt update
            sudo apt install kicad
    - name: Generate all kicad outputs
      run: ./scripts/generate_kicad_outputs.sh
    - name: Create release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
            gh release create "${{ env.AUTO_TAG_NAME }}"
            gh release upload "${{ env.AUTO_TAG_NAME }}" ./output/*

