name: Generate Files

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

env:
  AUTO_TAG_NAME: ${{ github.ref_name }}_${{ github.sha }}
  PROJ_NAME: ghost_bot

jobs:
  kicad_generation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Install Linux Dependencies
      run: |
            sudo add-apt-repository ppa:kicad/kicad-8.0-releases
            sudo apt update
            sudo apt install kicad
    - name: Generate PCB pdf
      run: kicad-cli pcb export pdf -l "*" ./pcb/ghost-bot.kicad_pcb -o ./pcb/ghost-bot.pcb.pdf
    - name: Generate SCH pdf
      run: kicad-cli sch export pdf ./pcb/ghost-bot.kicad_sch -o ./pcb/ghost-bot.sch.pdf
    - name: Create release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
            gh release create "${{ env.AUTO_TAG_NAME }}"
            gh release upload "${{ env.AUTO_TAG_NAME }}" ./pcb/ghost-bot.pcb.pdf ./pcb/ghost-bot.sch.pdf

